#!/bin/bash

# default values
devel_mode=0


usage()
{
  echo "Usage: install --devel-mode"
  exit 2
}


PARSED_ARGUMENTS=$(getopt --name install -o d --long devel-mode -- "$@")

VALID_ARGUMENTS=$?
if [ "$VALID_ARGUMENTS" != "0" ]; then
  usage
fi




eval set -- "$PARSED_ARGUMENTS"
while :
do
  case "$1" in
    --devel-mode)   devel_mode=1      ; shift   ;;
    # -- means the end of the arguments; drop this, and break out of the while loop
    --) shift; break ;;
    # If invalid options were passed, then getopt should have reported an error,
    # which we checked as VALID_ARGUMENTS when getopt was called...
    *) echo "Unexpected option: $1 - this should not happen."
       usage ;;
  esac
done

if (( $devel_mode == 0 || $# != 0 )); then
    usage
fi

script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )"
echo #script_dir

# we are in devel mode
mkdir --parents "$HOME"/.local/bin
ln --symbolic --force "$script_dir"/base/bin/* "$HOME"/.local/bin



